### PR TITLE
You derped a bit and forgot to remove Tile Entities

### PR DESCRIPTION
**Pull request by wasliebob**
You forgot to remove tiles on block break, if you don't want pr's feel free to ignore this.

### CODE REVIEW

**Comment by Aroma1997** [comment]
That may explain a lot...

**Comment by wasliebob** [comment]
I might have derped myself a bit i think something else is wrong let me check it.

**Comment by Player3324** [comment]
Actually that's not quite, right. The super call already handles the TE removal.

For IC2 integration I highly recommend switching to BasicSource, just like https://github.com/ForestryMC/ForestryMC/blob/master/forestry_common/energy/forestry/energy/gadgets/MachineGenerator.java

**Comment by Aroma1997** [comment]
Ok, so it doesn't explain a lot.
And I might look into that BasicSource, but ATM, I'm busy with RL stuff and have things higher on my todo list.

**Pull request merged**
