### PR TITLE
Perfomace fix for servers with small TPS.

### PR DESCRIPTION
**Pull request by ghost**
As we know, minecraft server while loop should do 20 iterations per seconds, but if server is loaded, big or etc, server iterations per seconds will dramatically reduced. To prevent mod from lagging, we change tile update logic from ticks to milliseconds. So even if tick reducted, all should be fine. Same logic has Bukkit Furnace https://github.com/MinecraftPortCentral/MCPC-Plus-Legacy/blob/master/src/minecraft/net/minecraft/tileentity/TileEntityFurnace.java#L278. Let us be awesome <3

### CODE REVIEW

**Comment by ghost** [comment]
I think, must change from System.currentTimeMillis to System.currentTimeMillis / 1000L. But this will change ticks from 64 to 60.

**Comment by Aroma1997** [comment]
Yes.
One problem would then be, if the server is down, it will do more updates relative to ticks.

**Comment by ghost** [comment]
It's not true. Because:

``` java
private long lastUpdate = System.currentTimeMillis();
```

Also, i would very thank you, if you will compile my pull with 1.5.2 build. Because, i fill my self very painful with mods compiling.

**Comment by Aroma1997** [comment]
If you have a normal TPS, it will (let's say) update once every 3 seconds, so once every 60 ticks.
If you have a low TPS (half tick time), it will still (let's say) update once every 3 seconds, but that is once every 30 ticks, so it's even worse.
If you would do something like that, you would also have to use the System seconds (or 1000 Millis), not millis, cause the way you do it, it tries to refresh once every 3 milliseconds, which is basically 1000 times in 3 seconds.

**Pull request closed without merging**
